components/mdns/examples:
  disable:
    - if: IDF_TARGET in ["esp32h2"]

components/mdns/tests/unit_test:
  disable:
    - if: IDF_TARGET in ["esp32h2"]

components/mdns/tests/test_apps:
  disable:
    - if: IDF_TARGET in ["esp32h2"]
